//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     Version: 1.3501.16.0
//
//     Project:     NH_Boardroom_TST1080
//     Version:     1.0.0.0
//     Sdk:         CH5:2.11.1
//     Strategy:    Modern
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using System;
using System.Collections.Generic;
using System.Linq;

namespace NH_Boardroom_TST1080
{
    /// <summary>
    /// Common Interface for Root Contracts.
    /// </summary>
    public interface IContract
    {
        object UserObject { get; set; }
        void AddDevice(BasicTriListWithSmartObject device);
        void RemoveDevice(BasicTriListWithSmartObject device);

        /// <summary>
        /// Fires on ANY activity on the panel.
        /// </summary>
        event EventHandler<EventArgs> Activity;
    }

    /// <summary>
    /// Root contract giving access to top level project items such as Pages and global Widgets.
    /// </summary>
    public sealed class Contract : IContract, IDisposable
    {
        #region Components

        private ComponentMediator ComponentMediator { get; set; }

        public NH_Boardroom_TST1080.ISidebar Sidebar { get { return (NH_Boardroom_TST1080.ISidebar)InternalSidebar; } }
        private NH_Boardroom_TST1080.Sidebar InternalSidebar { get; set; }

        public NH_Boardroom_TST1080.BlurayControl.IBlurayControl BlurayControl { get { return (NH_Boardroom_TST1080.BlurayControl.IBlurayControl)InternalBlurayControl; } }
        private NH_Boardroom_TST1080.BlurayControl.BlurayControl InternalBlurayControl { get; set; }

        public NH_Boardroom_TST1080.TunerControl.ITunerControl TunerControl { get { return (NH_Boardroom_TST1080.TunerControl.ITunerControl)InternalTunerControl; } }
        private NH_Boardroom_TST1080.TunerControl.TunerControl InternalTunerControl { get; set; }

        #endregion

        #region Construction and Initialization

        public Contract()
            : this(new List<BasicTriListWithSmartObject>().ToArray())
        {
        }

        public Contract(BasicTriListWithSmartObject device)
            : this(new [] { device })
        {
        }

        public Contract(BasicTriListWithSmartObject[] devices)
        {
            if (devices == null)
                throw new ArgumentNullException("Devices is null");

            ComponentMediator = new ComponentMediator();
            ComponentMediator.ConfigureActivityEvent(onActivity);

            InternalSidebar = new NH_Boardroom_TST1080.Sidebar(ComponentMediator, 10);

            InternalBlurayControl = new NH_Boardroom_TST1080.BlurayControl.BlurayControl(ComponentMediator, 11);

            InternalTunerControl = new NH_Boardroom_TST1080.TunerControl.TunerControl(ComponentMediator, 16);


            for (int index = 0; index < devices.Length; index++)
            {
                AddDevice(devices[index]);
            }
        }

        /// <summary>
        /// Fires on ANY activity on the panel.
        /// </summary>
        public event EventHandler<EventArgs> Activity;
        private void onActivity(GenericBase currentDevice, SmartObjectEventArgs args)
        {
            var handler = Activity;
            if (handler != null)
                handler(currentDevice, args);
        }
        #endregion

        #region Standard Contract Members

        public object UserObject { get; set; }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            InternalSidebar.AddDevice(device);
            InternalBlurayControl.AddDevice(device);
            InternalTunerControl.AddDevice(device);

        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            InternalSidebar.RemoveDevice(device);
            InternalBlurayControl.RemoveDevice(device);
            InternalTunerControl.RemoveDevice(device);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            InternalSidebar.Dispose();
            InternalBlurayControl.Dispose();
            InternalTunerControl.Dispose();

            ComponentMediator.Dispose(); 
        }

        #endregion
    }
}

